### ISSUE TITLE
All the Caldera Forms Migrated All at Once, Even Though Selected Only One!

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#278]
As the title suggests - during the migration process I selected only one form - no matter if by clicking the button next to it or using the checkbox and then the bottom button - but all the forms were imported. I used both selection methods (I restored the site from the backup between the both tests) just to be sure.

Considering the migration process resets and updates previously imported forms again, you can imagine how unfortunate this bug is! 

I'm 100% sure this was not the case in previous versions - this is not the first time I'm migrating forms from Caldera. I'm on the versions 4.3.24 / 4.3.23.

Please fix this ASAP. On my other site I'm right in the middle of the migration process from caldera (20+ forms), half of the forms are imported and updated and I'm glad this happened not there, but on my test site, otherwise my work would be ruined!

**Comment by black-eye** [comment]
**Update:** so I downgraded to the version combo 4.3.22 / 4.3.21 an the single form imports work fine there. So the problem was introduced by the last version (not sure wheather there was another major versin in between, the changelogs are rather tricky - pro changelog is nowhere to be found...).

**Comment by nkb-bd** [comment]
Fixed in our Dev branch

**Comment by black-eye** [comment]
> Fixed in our Dev branch, please open a support ticket if you need a beta version

Can I ask, when the update will be available? Tested today (v 4.3.25/4.3.23] and the issue is still there...
Thanks

**Comment by black-eye** [comment]
@nkb-bd Any updates on this issue, please?
