### ISSUE TITLE
Numeric field does not show decimal point when using iOS

### ISSUE THREAD

**Issue by ambulancePilot** [fluentform/fluentform#291]
Not sure if I am missing something basic here, but the decimal point issue with iOS is well known so I can't understand why this isn't accounted for in the input field code. inputmode="decimal" is needed to show the proper keyboard in iOS but obviously I cannot specify this using the provided front-end.

Suggestions and/or a fix would be appreciated. Thank you.

**Comment by nkb-bd** [comment]
Add this code to your function.php file and let me know if it works.
add_filter('fluentform_disable_inputmode', function () {
    return $true
});
Thanks

**Comment by ambulancePilot** [comment]
Tha6n you for the fast response. Where do I find the function.php file? Thank you.

**Comment by nkb-bd** [comment]
You can try using a plugin like code snippet or something similar to insert the code or you can find function.php file from Appearances, then click Theme Editor. If you have no coding experience try using the plugin.
Thanks

**Comment by ambulancePilot** [comment]
I wasn't aware you wanted me to modify my theme files. I assumed your
plug-in had a function.php file.

I would have just preferred the physical location of the function.php file
so that I can access it through FTP, but regardless I understand what you
are talking about now.

I will try it when I get home and let you know if it works. Thank you.

**Comment by ambulancePilot** [comment]
I am getting this error when trying to save functions.php

Your PHP code changes were rolled back due to an error on line 505 of file wp-content/themes/wilson/functions.php. Please fix and try saving again.

syntax error, unexpected '}', expecting ';'

Please let me know if I am doing something wrong or if you need to rework the code snippet you provided. Thank you very much.

**Comment by ambulancePilot** [comment]
The code snippet you provided me was missing a semicolon on line 2.

I have added the code to my functions.php file, is there anything else I need to do in order to get the decimal to show up on an iOS phone when inputting into a numeric field?

**Comment by nkb-bd** [comment]
Yeah sorry for that I updated the code ,use the code and no nothing else is needed it should work

**Comment by ambulancePilot** [comment]
Thank you very much, I will give it a try and report back. Thanks for the great plug in, I find it very useful.

**Comment by ambulancePilot** [comment]
Unfortunately it did not work. I created a repeater field with a numeric input and on iOS the decimal point still does not show on the keyboard when inputting data into the field. On Android, the correct keyboard shows.

Your continued assistance is appreciated!

**Comment by ambulancePilot** [comment]
Kind sir, are you able to fix this? If not I will need to request a refund as the product isn't functional as per my need.
